name: CI Trigger

on:
  issue_comment:
    types: [created]

jobs:

  trigger-workflow:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/ci test')

    steps:
      - name: Fetch Pull Request Info
        id: get_pr
        run: |
          PR_INFO=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}) \
            && HEAD_SHA=$(echo $PR_INFO | jq -r '.head.sha') \
            && HEAD_REF=$(echo $PR_INFO | jq -r '.head.ref') \
            && echo "::set-output name=head_sha::$HEAD_SHA" \
            && echo "::set-output name=head_ref::$HEAD_REF"

      - name: Create CI Check
        id: create_check
        run: |
          CHECK_RUN_ID=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -X POST https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{"name":"CI","head_sha":"${{ steps.get_pr.outputs.head_sha }}"}'
            | jq -r '.id') \
            && echo "::set-output name=check_run_id::$CHECK_RUN_ID"

      - name: Trigger CI Workflow
        run: |
          curl -s -H 'Authorization: token ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci.yml/dispatches \
            -d '{"ref":"${{ steps.get_pr.outputs.head_ref }}","inputs":{"check_run_id":"${{ steps.create_check.outputs.check_run_id }}"}}'
