name: CI

on:
  workflow_dispatch:
    inputs:
      check-run-id:
        description: Check Run ID
        required: false

jobs:
  check-in:
    name: Check In
    runs-on: ubuntu-latest
    if: github.event.inputs.check-run-id

    steps:
      - name: Get Current Run
        id: get-run
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repository}/actions/runs/{run_id}
          repository: ${{ github.repository }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CI Check
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: in_progress
          details_url: ${{ fromJSON(steps.get-run.outputs.data).html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check-in]
    if: always()
    steps:
      - name: Run a one-line script
        run: |
          echo "Working"
          sleep 5

      - name: Run a one-line script
        run: |
          echo "Working 2"
          sleep 5

      - name: Run a one-line script
        run: |
          echo "Working 3"
          sleep 5

  check-out:
    name: Check Out
    runs-on: ubuntu-latest
    if: github.event.inputs.check-run-id || cancelled()
    needs: [build]
    
    steps:
      - name: Update CI Check - Success
        if: success()
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: completed
          conclusion: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update CI Check - Failure
        if: failure()
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: completed
          conclusion: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update CI Check - Cancelled
        if: cancelled()
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: completed
          conclusion: cancelled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
