name: CI

on:
  workflow_dispatch:
    inputs:
      check-run-id:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          echo "Check run id: ${{ github.event.inputs.check-run-id }}"
