name: CI

on:
  workflow_dispatch:
    inputs:
      check_run_id:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world! ${{ toJSON(github.event) }}
