name: CI

on:
  workflow_dispatch:
    inputs:
      check-run-id:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update CI Check
        if: github.event.inputs.check-run-id
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: in_progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
#       - name: Get Current Check
#         id: get-check
#         uses: octokit/request-action@v2.x
#         with:
#           route: GET /repos/{repository}/check-runs/{check-run-id}
#           repository: ${{ github.repository }}
#           ref: ${{ github.event.ref }}
#           check-run-id: ${{ github.run_id }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get Checks
        id: get-checks
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repository}/commits/{ref}/check-runs
          repository: ${{ github.repository }}
          ref: ${{ github.event.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run a one-line script
        run: |
          echo "run ID: ${{ github.run_id }}"
          
      - name: Run a one-line script
        run: |
          echo "${{ fromJSON(steps.get-checks.outputs.data).check_runs[2].external_id }}"
          
      - name: Update CI Check
        if: github.event.inputs.check-run-id
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: completed
          conclusion: success
          external_id: ${{ fromJSON(steps.get-checks.outputs.data).check_runs[2].external_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
