name: CI

on:
  workflow_dispatch:
    inputs:
      check-run-id:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Current Run
        if: github.event.inputs.check-run-id
        id: get-run
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repository}/actions/runs/{run_id}
          repository: ${{ github.repository }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update CI Check
        if: github.event.inputs.check-run-id
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: in_progress
          details_url: ${{ fromJSON(steps.get-run.outputs.data).html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run a one-line script
        run: |
          echo "Working"
          sleep 15
      
      - name: Update CI Check
        if: github.event.inputs.check-run-id
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: completed
          conclusion: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
