name: CI

on:
  workflow_dispatch:
    inputs:
      check-run-id:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update CI Check
        if: github.event.inputs.check-run-id
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: in_progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run a one-line script
        run: |
          echo ${{ toJSON(github.event) }}
          sleep 15
      
      - name: Get Checks
        id: get-checks
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repository}/commits/{ref}/check-runs
          repository: ${{ github.repository }}
          ref: ${{ github.event.workflow_run.head_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CI Check
        if: github.event.inputs.check-run-id
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: completed
          conclusion: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
