name: CI

on:
  workflow_dispatch:
    inputs:
      check-run-id:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update CI Check
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: in_progress
          conclusion: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run a one-line script
        run: |
          echo "Check run id: ${{ github.event.inputs.check-run-id }}"
          
      - name: Update CI Check
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repository}/check-runs/${{ github.event.inputs.check-run-id }}
          repository: ${{ github.repository }}
          status: completed
          conclusion: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
