name: Manage Check Runs

on:
  workflow_run:
    workflows: ["CI"]

jobs:

  on-workflow-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'requested'

    steps:
      - name: Create CI Check
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/check-runs
          repository: ${{ github.repository }}
          name: zlib
          head_sha: ${{ github.event.workflow_run.head_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
