name: Manage Check Runs

on:
  workflow_run:
    workflows: ["CI"]

jobs:

  on-workflow-requested:
    name: On Workflow Requested
    runs-on: ubuntu-latest
    if: github.event.action == 'requested'

    steps:
      - name: Create CI Check
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/check-runs
          repository: ${{ github.repository }}
          name: SOME CHECK
          head_sha: ${{ github.event.workflow_run.head_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
  on-workflow-completed:
    name: On Workflow Completed
    runs-on: ubuntu-latest
    if: github.event.action == 'completed'

    steps:
      - name: Get Checks
        id: get-checks
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repository}/commits/{ref}/check-runs
          repository: ${{ github.repository }}
          ref: ${{ github.event.workflow_run.head_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Output
        run: |
          echo "${{ toJSON(github.event) }}"
          echo "${{ toJSON(steps.get-checks.data) }}"
