name: swift
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to fetch'     
        required: false
      branch_spec:
        description: 'Branch specification (main, 5.4, 5.3)'
        required: true
        default: 'main'
      runs_on:
        description: 'Runner label (windows-latest, self-hosted)'
        required: true
        default: 'windows-latest'
      check_run_id:
        description: Check Run ID
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
