name: Windows Env

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Run a one-line script
        run: |
          echo Start...
          :: dir "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC"
          dir %TEMP%
          
          echo Running installer...
          cmd.exe /d /e:on /v:off /s /c ""%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vs_installer.exe" modify --quiet --norestart --nocache --installPath="%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise" --add Microsoft.VisualStudio.Component.VC.14.28.16.9.x86.x64 --add Microsoft.VisualStudio.Component.VC.14.28.16.9.ATL"
          echo Result: %ERRORLEVEL%
          
          :check_vc_dir
          dir /b /s "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\lib\x64\vccorlib.lib"
          if errorlevel 1 goto wait
          echo Success
          exit /b
          
          :wait
          dir /b /s "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\*"
          echo Waiting...
          ping -n 60 127.0.0.1 >NUL
          goto check_vc_dir
          
          :: type %TEMP%\dd_*
