name: Windows Env

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Run a one-line script
        run: |
          echo Start...
          :: dir "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC"
          dir %TEMP%
          
          echo Running installer...
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vs_installer.exe" modify --quiet --norestart ^
           --installPath="%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise" ^
           --add Microsoft.VisualStudio.Component.VC.14.28.16.9.x86.x64;includeRecommended;includeOptional ^
           --add Microsoft.VisualStudio.Component.VC.14.28.16.9.ATL;includeRecommended;includeOptional
           
          echo Result: %ERRORLEVEL%
          
          :: dir "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC"
          type %TEMP%\dd_*
