name: Windows Env

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Run a one-line script
        run: |
          echo "Hello, world!"
